export const dishes = Object.freeze({
  FETCH_DISHES: "FETCH_DISHES",
  FETCH_DISHES_SUCCESS: "FETCH_DISHES_SUCCESS",
  FETCH_DISHES_ERROR: "FETCH_DISHES_ERROR",
  SET_DISH_TO_FAVOURITE:"SET_DISH_TO_FAVOURITE",
  ADD_DISH:"ADD_DISH",
  REMOVE_DISH:"REMOVE_DISH",
  EDIT_DISH:"EDIT_DISH",
})